version: "3.9"
services:
  frontend:
    build: ./services/frontend
    environment:
      - ELIGIBILITY_API_ENDPOINT=http://eligibility-service:8100
    ports:
      - "8000:8000"
    links:
      - eligibility-service
  eligibility-service:
    build: ./services/dummy
    ports:
      - "8100:8100"
  jupyter:
    build: ./services/support/jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work:z
    links:
      - mlflow
  mlflow:
    build: ./services/support/mlflow
    ports:
      - "5500:5500"