apiVersion: apps/v1
kind: Deployment
metadata:
  name: eligibility-service-deployment
  labels:
    app: eligibility-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eligibility-service
  template:
    metadata:
      labels:
        app: eligibility-service
    spec:
      containers:
        - name: frontend
          image: fluescher/sustaino-dummy-service
          ports:
            - containerPort: 8100
---
kind: Service
apiVersion: v1
metadata:
  name: eligibility-service
spec:
  selector:
    app: eligibility-service
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
  type: ClusterIP


